ead:
  serviceRegistry:
    username: serviceregistry
    password: ead123sr
  auth:
    jwtSecret: t7w!z%C&F)J@NcRfUjXn2r5u8x/A?D(G-KaPdSgVkYp3s6v9y$B&E)H@MbQeThWm
    jwtExpirationMs: 14400000
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost


